Connect through url, testMe function give error and no welcome message
