Connect through url, testMe function gives error and no welcome message
